services:
  core:
    build:
      context: ../..
      dockerfile: utils/docker/core.Dockerfile
      args:
        SWIFT_BUILD_CONFIGURATION: ${SWIFT_BUILD_CONFIGURATION:-release}
    # env_file:
    #   - ../../.env
    environment:
      SWIFT_BUILD_CONFIGURATION: ${SWIFT_BUILD_CONFIGURATION:-release}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      BRAVE_API_KEY: ${BRAVE_API_KEY:-}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY:-}
    ports:
      - "25101:25101"
    volumes:
      - ../../.sloppy:/root/.sloppy

  dashboard:
    build:
      context: ../..
      dockerfile: utils/docker/dashboard.Dockerfile
    # env_file:
    #   - ../../.env
    ports:
      - "25102:25102"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      BRAVE_API_KEY: ${BRAVE_API_KEY:-}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY:-}
    depends_on:
      - core

# volumes:
#   core_data:
